### ISSUE TITLE
Understanding the function "split_oberved_unknown" in data_sim/raw/prepare_data.py

### ISSUE THREAD

**Issue by Vishruth-Sham** [yaochenzhu/Deep-Deconf#2]
Why do we split the val and test data into observed and unkown? I can understand the code but what is the reasoning behind this split?

**Comment by yaochenzhu** [comment]
Hi,

Thanks for asking. The reason is that, the evaluation of recommendation performance follows the "strong generalization" setting of the Multi-VAE paper [1], where ratings from validation and test users are not included in the training set. However, we still need to observe some ratings (observed) from these users to infer the user latent variables, and from which decode the ratings for predictions. The  predictions are compared with the unknown ones (unknown) to select the model (val data) and measure the recommendation performance (test data).

Let me know if you have further questions.

Best,
Yaochen

[1] Liang, Dawen, et al. "Variational autoencoders for collaborative filtering." Proceedings of the 2018 world wide web conference. 2018.
